WARNING 2025-10-05 22:10:14,817 log 26666 138158821861056 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-05 22:10:14,818 basehttp 26666 138158821861056 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-05 22:41:43,560 log 29875 125229519075008 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-05 22:41:43,561 basehttp 29875 125229519075008 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-05 22:44:46,822 log 30149 139150420342464 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-05 22:44:46,823 basehttp 30149 139150420342464 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-05 22:47:08,333 log 30149 139150420342464 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-05 22:47:08,333 basehttp 30149 139150420342464 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-05 22:48:03,467 log 30149 139150420342464 Not Found: /favicon.ico
WARNING 2025-10-05 22:48:03,467 basehttp 30149 139150420342464 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-05 22:48:19,192 log 30149 139150420342464 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-05 22:48:19,193 basehttp 30149 139150420342464 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-05 22:48:25,599 log 30149 139150420342464 Not Found: /favicon.ico
WARNING 2025-10-05 22:48:25,599 basehttp 30149 139150420342464 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-05 22:54:52,746 log 31257 125356723922624 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-05 22:54:52,746 basehttp 31257 125356723922624 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-06 21:18:56,763 basehttp 10535 140072116549312 "GET /static/lib/material-dashboard-pro/assets/img/favicon.png HTTP/1.1" 404 2074
WARNING 2025-10-06 21:19:17,934 log 10535 140072036857536 Not Found: /favicon.ico
WARNING 2025-10-06 21:19:17,935 basehttp 10535 140072036857536 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-06 21:26:53,408 log 10535 140072036857536 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-06 21:26:53,408 basehttp 10535 140072036857536 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
ERROR 2025-10-06 21:42:30,367 log 12674 130056757180096 Internal Server Error: /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/
Traceback (most recent call last):
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list_site' not found. 'list_site' is not a valid view function or pattern name.
ERROR 2025-10-06 21:42:30,370 basehttp 12674 130056757180096 "GET /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/ HTTP/1.1" 500 233948
WARNING 2025-10-06 22:08:56,498 log 12970 131234413934272 Not Found: /company/detail/e1d4be7a-df94-4bc8-8b42-262b4dbd7619/dashboard.html
WARNING 2025-10-06 22:08:56,498 basehttp 12970 131234413934272 "GET /company/detail/e1d4be7a-df94-4bc8-8b42-262b4dbd7619/dashboard.html HTTP/1.1" 404 7193
WARNING 2025-10-06 22:12:21,044 log 12970 131234413934272 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-06 22:12:21,045 basehttp 12970 131234413934272 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-06 22:12:53,271 log 12970 131234413934272 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-06 22:12:53,271 basehttp 12970 131234413934272 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-06 22:14:27,148 log 12970 131234413934272 Not Found: /company/detail/e1d4be7a-df94-4bc8-8b42-262b4dbd7619/dashboard.html
WARNING 2025-10-06 22:14:27,148 basehttp 12970 131234413934272 "GET /company/detail/e1d4be7a-df94-4bc8-8b42-262b4dbd7619/dashboard.html HTTP/1.1" 404 7193
WARNING 2025-10-06 22:32:02,234 log 15955 129629353408192 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-06 22:32:02,234 basehttp 15955 129629353408192 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-06 22:34:37,161 log 15955 129629353408192 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-06 22:34:37,162 basehttp 15955 129629353408192 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-06 22:35:41,571 log 15955 129629353408192 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-06 22:35:41,572 basehttp 15955 129629353408192 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-06 22:35:45,108 log 15955 129629353408192 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-06 22:35:45,108 basehttp 15955 129629353408192 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-08 19:40:57,715 basehttp 8491 133323498190528 "GET /static/lib/material-dashboard-pro/assets/img/favicon.png HTTP/1.1" 404 2074
WARNING 2025-10-08 19:41:16,043 log 8491 133323489797824 Not Found: /favicon.ico
WARNING 2025-10-08 19:41:16,043 basehttp 8491 133323489797824 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-08 19:41:46,298 log 8491 133323489797824 Not Found: /company/detail/e1d4be7a-df94-4bc8-8b42-262b4dbd7619/dashboard.html
WARNING 2025-10-08 19:41:46,299 basehttp 8491 133323489797824 "GET /company/detail/e1d4be7a-df94-4bc8-8b42-262b4dbd7619/dashboard.html HTTP/1.1" 404 7193
ERROR 2025-10-08 20:41:15,146 log 12848 126918699513536 Internal Server Error: /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/
Traceback (most recent call last):
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    if match:
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/utils/functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'site_detail' not found. 'site_detail' is not a valid view function or pattern name.
ERROR 2025-10-08 20:41:15,150 basehttp 12848 126918699513536 "GET /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/ HTTP/1.1" 500 205507
WARNING 2025-10-08 20:43:09,276 log 12962 127480568477376 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-08 20:43:09,276 basehttp 12962 127480568477376 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-08 20:43:55,443 log 12962 127480568477376 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-08 20:43:55,445 basehttp 12962 127480568477376 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-08 20:44:06,882 log 12962 127480568477376 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-08 20:44:06,883 basehttp 12962 127480568477376 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-08 21:20:55,896 log 16211 127608089999040 Method Not Allowed (POST): /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/
WARNING 2025-10-08 21:20:55,914 basehttp 16211 127608089999040 "POST /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/ HTTP/1.1" 405 0
WARNING 2025-10-08 21:21:56,939 log 16211 127608081606336 Method Not Allowed (POST): /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/
WARNING 2025-10-08 21:21:56,953 basehttp 16211 127608081606336 "POST /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/ HTTP/1.1" 405 0
WARNING 2025-10-08 21:24:48,095 log 16211 127608089999040 Not Found: /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/[object HTMLInputElement]
WARNING 2025-10-08 21:24:48,096 basehttp 16211 127608089999040 "POST /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/[object%20HTMLInputElement] HTTP/1.1" 404 7248
WARNING 2025-10-08 21:40:12,382 log 6611 126381012809408 Not Found: /favicon.ico
WARNING 2025-10-08 21:40:12,383 basehttp 6611 126381012809408 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-08 21:40:19,784 log 6611 126381004416704 Not Found: /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/[object HTMLInputElement]
WARNING 2025-10-08 21:40:19,784 basehttp 6611 126381004416704 "POST /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/[object%20HTMLInputElement] HTTP/1.1" 404 7248
WARNING 2025-10-08 21:42:04,328 log 7136 133856329987776 Not Found: /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/[object HTMLInputElement]
WARNING 2025-10-08 21:42:04,334 basehttp 7136 133856329987776 "POST /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/[object%20HTMLInputElement] HTTP/1.1" 404 7248
WARNING 2025-10-08 21:43:01,234 log 7136 133856329987776 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-08 21:43:01,234 basehttp 7136 133856329987776 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-08 21:43:53,698 log 7136 133856329987776 Not Found: /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/[object HTMLInputElement]
WARNING 2025-10-08 21:43:53,698 basehttp 7136 133856329987776 "POST /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/[object%20HTMLInputElement] HTTP/1.1" 404 7248
WARNING 2025-10-08 21:47:55,891 log 7136 133856329987776 Not Found: /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/[object HTMLInputElement]
WARNING 2025-10-08 21:47:55,892 basehttp 7136 133856329987776 "POST /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/[object%20HTMLInputElement] HTTP/1.1" 404 7248
WARNING 2025-10-08 21:48:19,711 log 7136 133856329987776 Not Found: /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/[object HTMLInputElement]
WARNING 2025-10-08 21:48:19,712 basehttp 7136 133856329987776 "POST /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/[object%20HTMLInputElement] HTTP/1.1" 404 7248
WARNING 2025-10-08 21:56:25,236 log 7136 133856321595072 Method Not Allowed (POST): /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/
WARNING 2025-10-08 21:56:25,242 basehttp 7136 133856321595072 "POST /company/detail_site/93660c76-05d5-4528-8fbe-55633e75018a/ HTTP/1.1" 405 0
WARNING 2025-10-09 06:49:04,841 basehttp 7463 131371691407040 "GET /static/lib/material-dashboard-pro/assets/img/favicon.png HTTP/1.1" 404 2074
WARNING 2025-10-09 06:49:26,516 log 7463 131371683014336 Not Found: /favicon.ico
WARNING 2025-10-09 06:49:26,517 basehttp 7463 131371683014336 "GET /favicon.ico HTTP/1.1" 404 3449
ERROR 2025-10-09 07:15:55,049 log 9182 139093832890048 Internal Server Error: /company/update_stage/5e801282-f614-4c65-a985-7bd28bac2ee4/
Traceback (most recent call last):
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/company/views/stage/views.py", line 65, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/mixins.py", line 23, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/edit.py", line 202, in get
    return super().get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/company/views/stage/views.py", line 85, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/company/forms.py", line 165, in __init__
    self.site = kwargs.pop('site')
                ^^^^^^^^^^^^^^^^^^
KeyError: 'site'
ERROR 2025-10-09 07:15:55,051 basehttp 9182 139093832890048 "GET /company/update_stage/5e801282-f614-4c65-a985-7bd28bac2ee4/ HTTP/1.1" 500 129933
ERROR 2025-10-09 07:15:57,604 log 9182 139093832890048 Internal Server Error: /company/update_stage/5e801282-f614-4c65-a985-7bd28bac2ee4/
Traceback (most recent call last):
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/company/views/stage/views.py", line 65, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/mixins.py", line 23, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/edit.py", line 202, in get
    return super().get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/company/views/stage/views.py", line 85, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/company/forms.py", line 165, in __init__
    self.site = kwargs.pop('site')
                ^^^^^^^^^^^^^^^^^^
KeyError: 'site'
ERROR 2025-10-09 07:15:57,605 basehttp 9182 139093832890048 "GET /company/update_stage/5e801282-f614-4c65-a985-7bd28bac2ee4/ HTTP/1.1" 500 129933
ERROR 2025-10-09 07:20:01,519 log 9182 139093832890048 Internal Server Error: /company/update_stage/5e801282-f614-4c65-a985-7bd28bac2ee4/
Traceback (most recent call last):
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/company/views/stage/views.py", line 65, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/mixins.py", line 23, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/edit.py", line 202, in get
    return super().get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/company/views/stage/views.py", line 85, in get_context_data
    context = super().get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/company/forms.py", line 165, in __init__
    self.site = kwargs.pop('site')
                ^^^^^^^^^^^^^^^^^^
KeyError: 'site'
ERROR 2025-10-09 07:20:01,520 basehttp 9182 139093832890048 "GET /company/update_stage/5e801282-f614-4c65-a985-7bd28bac2ee4/ HTTP/1.1" 500 129933
WARNING 2025-10-09 07:54:23,664 log 12236 137997687191232 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-09 07:54:23,664 basehttp 12236 137997687191232 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-09 08:16:25,147 log 18093 136440541345472 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-09 08:16:25,148 basehttp 18093 136440541345472 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-09 08:25:48,767 log 18093 136440541345472 Not Found: /user/update-password/5b040378-73b0-43a2-a90e-5cc75dc115a7/
WARNING 2025-10-09 08:25:48,767 basehttp 18093 136440541345472 "GET /user/update-password/5b040378-73b0-43a2-a90e-5cc75dc115a7/ HTTP/1.1" 404 7131
ERROR 2025-10-09 09:43:43,750 log 18093 136440541345472 Internal Server Error: /user/training/download/
Traceback (most recent call last):
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/mixins.py", line 23, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/user/views/training/views.py", line 131, in get
    url = urlopen(link)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
ERROR 2025-10-09 09:43:43,753 basehttp 18093 136440541345472 "GET /user/training/download/?id=b0302388-97e4-4303-9a61-69bd79f631b0&type=support_training HTTP/1.1" 500 128680
WARNING 2025-10-09 10:24:44,731 basehttp 6348 129096864495296 "GET /static/lib/material-dashboard-pro/assets/img/favicon.png HTTP/1.1" 404 2074
WARNING 2025-10-09 10:24:56,097 log 6348 129096864495296 Not Found: /favicon.ico
WARNING 2025-10-09 10:24:56,097 basehttp 6348 129096864495296 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-10 06:41:10,814 basehttp 5760 140127670105792 "GET /static/lib/material-dashboard-pro/assets/img/favicon.png HTTP/1.1" 404 2074
WARNING 2025-10-10 06:41:22,173 log 5760 140127749797568 Not Found: /favicon.ico
WARNING 2025-10-10 06:41:22,174 basehttp 5760 140127749797568 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-10 06:51:54,442 log 5760 140127661713088 Not Found: /favicon.ico
WARNING 2025-10-10 06:51:54,442 basehttp 5760 140127661713088 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-10 06:59:29,479 log 5760 140127661713088 Not Found: /favicon.ico
WARNING 2025-10-10 06:59:29,479 basehttp 5760 140127661713088 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-10 07:04:30,755 log 5760 140127661713088 Not Found: /favicon.ico
WARNING 2025-10-10 07:04:30,756 basehttp 5760 140127661713088 "GET /favicon.ico HTTP/1.1" 404 3449
ERROR 2025-10-10 07:13:31,445 log 8771 135578352875200 Internal Server Error: /user/detail/ba551f61-2ecd-4370-8f62-9451f3fdf10f/
Traceback (most recent call last):
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column Training.training_status does not exist
LINE 1: ...ate_training", "Training"."date_training_expire", "Training"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 1016, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/template/defaulttags.py", line 199, in render
    len_values = len(values)
                 ^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column Training.training_status does not exist
LINE 1: ...ate_training", "Training"."date_training_expire", "Training"...
                                                             ^

ERROR 2025-10-10 07:13:31,449 basehttp 8771 135578352875200 "GET /user/detail/ba551f61-2ecd-4370-8f62-9451f3fdf10f/ HTTP/1.1" 500 284029
WARNING 2025-10-10 07:24:54,789 log 9125 126833574016704 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-10 07:24:54,790 basehttp 9125 126833574016704 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-10 07:34:14,489 log 9125 126833574016704 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-10 07:34:14,489 basehttp 9125 126833574016704 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
WARNING 2025-10-10 07:36:55,984 log 9125 126833574016704 Not Found: /.well-known/appspecific/com.chrome.devtools.json
WARNING 2025-10-10 07:36:55,985 basehttp 9125 126833574016704 "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 3560
ERROR 2025-10-10 07:38:14,905 log 9125 126833574016704 Internal Server Error: /user/competence/download/
Traceback (most recent call last):
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/mixins.py", line 23, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/venv_luka/lib/python3.11/site-packages/django/views/generic/base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eduard/DevelopProjects/lims/luka/core/user/views/competence/views.py", line 131, in get
    url = urlopen(link)
          ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
ERROR 2025-10-10 07:38:14,912 basehttp 9125 126833574016704 "GET /user/competence/download/?id=87232cc4-7092-436c-8cc2-f41c92e85e2f&type=support_competence HTTP/1.1" 500 128692
WARNING 2025-10-10 08:15:19,068 log 13057 138568675612352 Not Found: /favicon.ico
WARNING 2025-10-10 08:15:19,069 basehttp 13057 138568675612352 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-10 08:17:28,152 log 13057 138568694494912 Not Found: /favicon.ico
WARNING 2025-10-10 08:17:28,152 basehttp 13057 138568694494912 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-10 08:18:46,937 log 13414 132909767845568 Not Found: /favicon.ico
WARNING 2025-10-10 08:18:46,938 basehttp 13414 132909767845568 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-10 08:20:41,476 log 13414 132909776238272 Not Found: /favicon.ico
WARNING 2025-10-10 08:20:41,477 basehttp 13414 132909776238272 "GET /favicon.ico HTTP/1.1" 404 3449
WARNING 2025-10-10 08:22:40,120 log 13548 129643422144192 Not Found: /favicon.ico
WARNING 2025-10-10 08:22:40,120 basehttp 13548 129643422144192 "GET /favicon.ico HTTP/1.1" 404 3449
